/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mhe_simple_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s1[13] = {3, 3, 0, 2, 4, 7, 0, 1, 0, 1, 0, 1, 2};
static const casadi_int casadi_s2[12] = {3, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};

/* mhe_simple_model_expl_vde_forw:(i0[3],i1[3x3],i2[3x3],i3[3],i4)->(o0[3],o1[3x3,6nz],o2[3x3,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, *w4=w+7, w5, *w6=w+11, *w7=w+14, *w8=w+23, *w9=w+26, *w11=w+33, *w12=w+35, *w13=w+37, *w14=w+39, *w15=w+45;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[4][0] */
  w1 = arg[4] ? arg[4][0] : 0;
  /* #2: @2 = input[0][2] */
  w2 = arg[0] ? arg[0][2] : 0;
  /* #3: @1 = (@1/@2) */
  w1 /= w2;
  /* #4: @3 = 0 */
  w3 = 0.;
  /* #5: @4 = vertcat(@0, @1, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w3;
  /* #6: @0 = input[3][0] */
  w0 = arg[3] ? arg[3][0] : 0;
  /* #7: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #8: @5 = input[3][2] */
  w5 = arg[3] ? arg[3][2] : 0;
  /* #9: @6 = vertcat(@0, @3, @5) */
  rr=w6;
  *rr++ = w0;
  *rr++ = w3;
  *rr++ = w5;
  /* #10: @4 = (@4+@6) */
  for (i=0, rr=w4, cs=w6; i<3; ++i) (*rr++) += (*cs++);
  /* #11: output[0][0] = @4 */
  casadi_copy(w4, 3, res[0]);
  /* #12: @7 = input[1][0] */
  casadi_copy(arg[1], 9, w7);
  /* #13: {@4, @6, @8} = horzsplit(@7) */
  casadi_copy(w7, 3, w4);
  casadi_copy(w7+3, 3, w6);
  casadi_copy(w7+6, 3, w8);
  /* #14: {NULL, @0, @3} = vertsplit(@4) */
  w0 = w4[1];
  w3 = w4[2];
  /* #15: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #16: @0 = (@1/@2) */
  w0  = (w1/w2);
  /* #17: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #18: @3 = (-@3) */
  w3 = (- w3 );
  /* #19: output[1][1] = @3 */
  if (res[1]) res[1][1] = w3;
  /* #20: {NULL, @3, @5} = vertsplit(@6) */
  w3 = w6[1];
  w5 = w6[2];
  /* #21: output[1][2] = @3 */
  if (res[1]) res[1][2] = w3;
  /* #22: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #23: @5 = (-@5) */
  w5 = (- w5 );
  /* #24: output[1][3] = @5 */
  if (res[1]) res[1][3] = w5;
  /* #25: {NULL, @5, @3} = vertsplit(@8) */
  w5 = w8[1];
  w3 = w8[2];
  /* #26: output[1][4] = @5 */
  if (res[1]) res[1][4] = w5;
  /* #27: @0 = (@0*@3) */
  w0 *= w3;
  /* #28: @0 = (-@0) */
  w0 = (- w0 );
  /* #29: output[1][5] = @0 */
  if (res[1]) res[1][5] = w0;
  /* #30: @8 = zeros(3x3,3nz) */
  casadi_clear(w8, 3);
  /* #31: @6 = ones(3x1) */
  casadi_fill(w6, 3, 1.);
  /* #32: (@8[:3] = @6) */
  for (rr=w8+0, ss=w6; rr!=w8+3; rr+=1) *rr = *ss++;
  /* #33: @6 = @8' */
  casadi_trans(w8,casadi_s0, w6, casadi_s0, iw);
  /* #34: @9 = project(@6) */
  casadi_project(w6, casadi_s0, w9, casadi_s1, w);
  /* #35: @7 = input[2][0] */
  casadi_copy(arg[2], 9, w7);
  /* #36: {@6, @8, @4} = horzsplit(@7) */
  casadi_copy(w7, 3, w6);
  casadi_copy(w7+3, 3, w8);
  casadi_copy(w7+6, 3, w4);
  /* #37: {NULL, @0, @3} = vertsplit(@6) */
  w0 = w6[1];
  w3 = w6[2];
  /* #38: @1 = (@1/@2) */
  w1 /= w2;
  /* #39: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #40: @3 = (-@3) */
  w3 = (- w3 );
  /* #41: @10 = 00 */
  /* #42: @11 = vertcat(@0, @3, @10) */
  rr=w11;
  *rr++ = w0;
  *rr++ = w3;
  /* #43: {NULL, @0, @3} = vertsplit(@8) */
  w0 = w8[1];
  w3 = w8[2];
  /* #44: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #45: @3 = (-@3) */
  w3 = (- w3 );
  /* #46: @10 = 00 */
  /* #47: @12 = vertcat(@0, @3, @10) */
  rr=w12;
  *rr++ = w0;
  *rr++ = w3;
  /* #48: {NULL, @0, @3} = vertsplit(@4) */
  w0 = w4[1];
  w3 = w4[2];
  /* #49: @1 = (@1*@3) */
  w1 *= w3;
  /* #50: @1 = (-@1) */
  w1 = (- w1 );
  /* #51: @10 = 00 */
  /* #52: @13 = vertcat(@0, @1, @10) */
  rr=w13;
  *rr++ = w0;
  *rr++ = w1;
  /* #53: @14 = horzcat(@11, @12, @13) */
  rr=w14;
  for (i=0, cs=w11; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<2; ++i) *rr++ = *cs++;
  /* #54: @15 = project(@14) */
  casadi_project(w14, casadi_s2, w15, casadi_s1, w);
  /* #55: @9 = (@9+@15) */
  for (i=0, rr=w9, cs=w15; i<7; ++i) (*rr++) += (*cs++);
  /* #56: output[2][0] = @9 */
  casadi_copy(w9, 7, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_simple_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mhe_simple_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_simple_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_simple_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mhe_simple_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mhe_simple_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mhe_simple_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mhe_simple_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mhe_simple_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mhe_simple_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mhe_simple_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_simple_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mhe_simple_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_simple_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s4;
    case 3: return casadi_s3;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mhe_simple_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mhe_simple_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 52;
  return 0;
}

CASADI_SYMBOL_EXPORT int mhe_simple_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 52*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
