/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) system_2d_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s5[3] = {1, 0, 0};

/* system_2d_constr_h_fun_jac_uxt_zt:(i0[4],i1[2],i2[],i3[])->(o0,o1[6],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, w3, w4, *w5=w+6, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+20;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+2 : 0, 2, w0);
  /* #1: @1 = @0[0] */
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #2: @2 = sq(@1) */
  w2 = casadi_sq( w1 );
  /* #3: @3 = @0[1] */
  for (rr=(&w3), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #4: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #5: @2 = (@2+@4) */
  w2 += w4;
  /* #6: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #7: @5 = input[0][0] */
  casadi_copy(arg[0], 2, w5);
  /* #8: @4 = @5[0] */
  for (rr=(&w4), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #9: @6 = 2 */
  w6 = 2.;
  /* #10: @4 = (@4-@6) */
  w4 -= w6;
  /* #11: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #12: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #13: @8 = @5[1] */
  for (rr=(&w8), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #14: @9 = 2 */
  w9 = 2.;
  /* #15: @8 = (@8-@9) */
  w8 -= w9;
  /* #16: @9 = input[1][1] */
  w9 = arg[1] ? arg[1][1] : 0;
  /* #17: @10 = (@8*@9) */
  w10  = (w8*w9);
  /* #18: @7 = (@7+@10) */
  w7 += w10;
  /* #19: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #20: @2 = (@2+@7) */
  w2 += w7;
  /* #21: @7 = 20 */
  w7 = 20.;
  /* #22: @10 = @5[0] */
  for (rr=(&w10), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #23: @11 = 2 */
  w11 = 2.;
  /* #24: @10 = (@10-@11) */
  w10 -= w11;
  /* #25: @11 = @0[0] */
  for (rr=(&w11), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #26: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #27: @13 = @5[1] */
  for (rr=(&w13), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #28: @14 = 2 */
  w14 = 2.;
  /* #29: @13 = (@13-@14) */
  w13 -= w14;
  /* #30: @14 = @0[1] */
  for (rr=(&w14), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #31: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #32: @12 = (@12+@15) */
  w12 += w15;
  /* #33: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #34: @7 = (@7*@12) */
  w7 *= w12;
  /* #35: @2 = (@2+@7) */
  w2 += w7;
  /* #36: @7 = 64 */
  w7 = 64.;
  /* #37: @12 = @5[0] */
  for (rr=(&w12), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #38: @15 = 2 */
  w15 = 2.;
  /* #39: @12 = (@12-@15) */
  w12 -= w15;
  /* #40: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #41: @16 = @5[1] */
  for (rr=(&w16), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #42: @17 = 2 */
  w17 = 2.;
  /* #43: @16 = (@16-@17) */
  w16 -= w17;
  /* #44: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #45: @15 = (@15+@17) */
  w15 += w17;
  /* #46: @17 = 0.25 */
  w17 = 2.5000000000000000e-01;
  /* #47: @15 = (@15-@17) */
  w15 -= w17;
  /* #48: @7 = (@7*@15) */
  w7 *= w15;
  /* #49: @2 = (@2+@7) */
  w2 += w7;
  /* #50: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #51: @18 = zeros(6x1) */
  casadi_clear(w18, 6);
  /* #52: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #53: (@18[0] = @4) */
  for (rr=w18+0, ss=(&w4); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #54: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #55: (@18[1] = @8) */
  for (rr=w18+1, ss=(&w8); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #56: @5 = zeros(2x1) */
  casadi_clear(w5, 2);
  /* #57: @8 = 64 */
  w8 = 64.;
  /* #58: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #59: @16 = (@8*@16) */
  w16  = (w8*w16);
  /* #60: (@5[1] += @16) */
  for (rr=w5+1, ss=(&w16); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #61: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #62: @8 = (@8*@12) */
  w8 *= w12;
  /* #63: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #64: @8 = 40 */
  w8 = 40.;
  /* #65: @14 = (@8*@14) */
  w14  = (w8*w14);
  /* #66: (@5[1] += @14) */
  for (rr=w5+1, ss=(&w14); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #67: @11 = (@8*@11) */
  w11  = (w8*w11);
  /* #68: (@5[0] += @11) */
  for (rr=w5+0, ss=(&w11); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #69: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #70: (@5[1] += @9) */
  for (rr=w5+1, ss=(&w9); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #71: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #72: (@5[0] += @6) */
  for (rr=w5+0, ss=(&w6); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #73: @6 = @5[0] */
  for (rr=(&w6), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #74: (@18[2] = @6) */
  for (rr=w18+2, ss=(&w6); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #75: @6 = @5[1] */
  for (rr=(&w6), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #76: (@18[3] = @6) */
  for (rr=w18+3, ss=(&w6); rr!=w18+4; rr+=1) *rr = *ss++;
  /* #77: @5 = zeros(2x1) */
  casadi_clear(w5, 2);
  /* #78: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #79: (@5[1] += @13) */
  for (rr=w5+1, ss=(&w13); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #80: @8 = (@8*@10) */
  w8 *= w10;
  /* #81: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #82: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #83: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #84: (@5[1] += @3) */
  for (rr=w5+1, ss=(&w3); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #85: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #86: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #87: (@5[0] += @1) */
  for (rr=w5+0, ss=(&w1); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #88: @1 = @5[0] */
  for (rr=(&w1), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #89: (@18[4] = @1) */
  for (rr=w18+4, ss=(&w1); rr!=w18+5; rr+=1) *rr = *ss++;
  /* #90: @1 = @5[1] */
  for (rr=(&w1), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #91: (@18[5] = @1) */
  for (rr=w18+5, ss=(&w1); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #92: output[1][0] = @18 */
  casadi_copy(w18, 6, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int system_2d_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int system_2d_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int system_2d_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void system_2d_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int system_2d_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void system_2d_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void system_2d_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void system_2d_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int system_2d_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int system_2d_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real system_2d_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* system_2d_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* system_2d_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* system_2d_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* system_2d_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int system_2d_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}

CASADI_SYMBOL_EXPORT int system_2d_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 26*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
